/**
 * NYC Subway Stations Dataset
 * Each station includes: id, name, lines, borough, lat, lng,
 * svgNodeId (reference to SVG schematic node), funFact, and exits.
 *
 * Coordinates are WGS84 (GPS-accurate).
 * Lines are listed in alphabetical/numerical order.
 */

export const STATIONS = [
  // ─────────────────────────── MANHATTAN ────────────────────────────

  {
    id: 'inwood-207',
    name: 'Inwood-207 St',
    lines: ['A'],
    borough: 'Manhattan',
    lat: 40.8682, lng: -73.9195,
    svgNodeId: 'n-inwood',
    funFact: 'The Inwood Hill Park, steps from this station, contains Manhattan\'s last remaining natural forest and ancient Native American caves.',
    exits: ['Isham St & 207 St', 'Seaman Ave & 207 St'],
  },
  {
    id: 'dyckman-st',
    name: 'Dyckman St',
    lines: ['A'],
    borough: 'Manhattan',
    lat: 40.8647, lng: -73.9277,
    svgNodeId: 'n-dyckman',
    funFact: 'The Dyckman Farmhouse Museum, one block away, is the only remaining Dutch Colonial farmhouse in Manhattan, dating to the 1780s.',
    exits: ['Dyckman St & Broadway'],
  },
  {
    id: '181-st-a',
    name: '181 St',
    lines: ['A'],
    borough: 'Manhattan',
    lat: 40.8601, lng: -73.9337,
    svgNodeId: 'n-181-a',
    funFact: 'One of the deepest stations in the NYC subway at 178 feet below street level, accessible only by elevator.',
    exits: ['Fort Washington Ave & 181 St'],
  },
  {
    id: '168-st',
    name: '168 St-Washington Heights',
    lines: ['1', 'A', 'C'],
    borough: 'Manhattan',
    lat: 40.8404, lng: -73.9395,
    svgNodeId: 'n-168',
    funFact: 'The 1904 IRT elevated structure here once ran on wooden ties. The area above is home to the famous Audubon Ballroom where Malcolm X was assassinated in 1965.',
    exits: ['Broadway & 168 St', 'Fort Washington Ave & 168 St'],
  },
  {
    id: '145-st',
    name: '145 St',
    lines: ['A', 'B', 'C', 'D'],
    borough: 'Manhattan',
    lat: 40.8243, lng: -73.9419,
    svgNodeId: 'n-145',
    funFact: 'The stretch of Eighth Avenue near here was a hub of Harlem\'s Jazz Age in the 1920s–30s, lined with legendary clubs.',
    exits: ['St Nicholas Ave & 145 St', 'Edgecombe Ave & 145 St'],
  },
  {
    id: '125-st-abcd',
    name: '125 St',
    lines: ['A', 'B', 'C', 'D'],
    borough: 'Manhattan',
    lat: 40.8115, lng: -73.9526,
    svgNodeId: 'n-125-abcd',
    funFact: 'Known as the "Crossroads of the World" in Harlem, the Apollo Theater — the birthplace of stars from Ella Fitzgerald to James Brown — is just one block east.',
    exits: ['St Nicholas Ave & 125 St', 'Frederick Douglass Blvd & 125 St'],
  },
  {
    id: '125-st-456',
    name: '125 St',
    lines: ['4', '5', '6'],
    borough: 'Manhattan',
    lat: 40.8044, lng: -73.9376,
    svgNodeId: 'n-125-456',
    funFact: 'The El Barrio neighborhood above this station is the historic heart of New York City\'s Puerto Rican community, sometimes called "Spanish Harlem."',
    exits: ['Lexington Ave & 125 St'],
  },
  {
    id: '116-columbia',
    name: '116 St-Columbia University',
    lines: ['1'],
    borough: 'Manhattan',
    lat: 40.8079, lng: -73.9640,
    svgNodeId: 'n-116',
    funFact: 'Columbia University above was founded in 1754 as King\'s College — one of nine colonial colleges established before the American Revolution.',
    exits: ['Broadway & 116 St'],
  },
  {
    id: '96-st-123',
    name: '96 St',
    lines: ['1', '2', '3'],
    borough: 'Manhattan',
    lat: 40.7940, lng: -73.9723,
    svgNodeId: 'n-96',
    funFact: 'The Upper West Side neighborhood above began its transformation in the 1880s when the IRT Ninth Avenue El opened, bringing development to what was then farmland.',
    exits: ['Broadway & 96 St'],
  },
  {
    id: '81-st-museum',
    name: '81 St-Museum of Natural History',
    lines: ['B', 'C'],
    borough: 'Manhattan',
    lat: 40.7813, lng: -73.9739,
    svgNodeId: 'n-81-museum',
    funFact: 'The American Museum of Natural History above holds over 34 million specimens, including the world\'s largest collection of dinosaur fossils.',
    exits: ['Central Park West & 81 St', '77 St & Central Park West'],
  },
  {
    id: '72-st',
    name: '72 St',
    lines: ['1', '2', '3'],
    borough: 'Manhattan',
    lat: 40.7781, lng: -73.9816,
    svgNodeId: 'n-72',
    funFact: 'The Dakota apartment building at 72nd & Central Park West, just steps from this station, is where John Lennon lived — and was tragically shot — in December 1980.',
    exits: ['Broadway & 72 St'],
  },
  {
    id: '59-st-columbus',
    name: '59 St-Columbus Circle',
    lines: ['1', 'A', 'B', 'C', 'D'],
    borough: 'Manhattan',
    lat: 40.7682, lng: -73.9814,
    svgNodeId: 'n-59-cc',
    funFact: 'The Maine Monument at Columbus Circle was built in 1913 from salvage metal of the battleship USS Maine, whose sinking triggered the Spanish-American War.',
    exits: ['Broadway & 60 St', '8th Ave & 59 St', 'Central Park West & 59 St'],
  },
  {
    id: 'times-sq-42',
    name: 'Times Sq-42 St',
    lines: ['1', '2', '3', '7', 'N', 'Q', 'R', 'W', 'S'],
    borough: 'Manhattan',
    lat: 40.7556, lng: -73.9877,
    svgNodeId: 'n-times-sq',
    funFact: 'The Times Square station complex serves over 65 million annual riders — more than the entire population of France passing through each year.',
    exits: ['7th Ave & 42 St', 'Broadway & 42 St', '8th Ave & 42 St', '43rd St'],
  },
  {
    id: 'grand-central-42',
    name: '42 St-Grand Central',
    lines: ['4', '5', '6', '7', 'S'],
    borough: 'Manhattan',
    lat: 40.7527, lng: -73.9772,
    svgNodeId: 'n-grand-central',
    funFact: 'Grand Central Terminal above has 44 platforms on two underground levels, making it the largest train station in the world by number of platforms.',
    exits: ['Lexington Ave & 42 St', 'Park Ave & 42 St', 'Vanderbilt Ave & 42 St'],
  },
  {
    id: '34-penn',
    name: '34 St-Penn Station',
    lines: ['1', '2', '3'],
    borough: 'Manhattan',
    lat: 40.7506, lng: -73.9991,
    svgNodeId: 'n-penn',
    funFact: 'The old Penn Station demolished in 1963 was hailed as one of the greatest buildings in America. Its destruction directly led to the creation of New York City\'s Landmarks Preservation Commission.',
    exits: ['8th Ave & 34 St', '7th Ave & 34 St'],
  },
  {
    id: '34-herald',
    name: '34 St-Herald Sq',
    lines: ['B', 'D', 'F', 'M', 'N', 'Q', 'R', 'W'],
    borough: 'Manhattan',
    lat: 40.7499, lng: -73.9876,
    svgNodeId: 'n-herald',
    funFact: 'Macy\'s Herald Square, opened in 1902, is the second-largest department store in the world, covering an entire city block and 11 floors.',
    exits: ['Broadway & 34 St', '6th Ave & 34 St'],
  },
  {
    id: '23-st-ce',
    name: '23 St',
    lines: ['C', 'E'],
    borough: 'Manhattan',
    lat: 40.7452, lng: -73.9982,
    svgNodeId: 'n-23-ce',
    funFact: 'The Flatiron Building, visible from this station, was the tallest building in the world when completed in 1902 and helped give rise to the word "skyscraper."',
    exits: ['8th Ave & 23 St'],
  },
  {
    id: '14-union-sq',
    name: '14 St-Union Sq',
    lines: ['4', '5', '6', 'L', 'N', 'Q', 'R', 'W'],
    borough: 'Manhattan',
    lat: 40.7352, lng: -73.9896,
    svgNodeId: 'n-union-sq',
    funFact: 'Union Square has been the site of political rallies since the 1800s. It was the gathering point for over 100,000 New Yorkers the day after September 11, 2001.',
    exits: ['14 St & 4th Ave', '14 St & Broadway', '14 St & University Pl'],
  },
  {
    id: 'canal-st-ace',
    name: 'Canal St',
    lines: ['A', 'C', 'E'],
    borough: 'Manhattan',
    lat: 40.7228, lng: -74.0050,
    svgNodeId: 'n-canal',
    funFact: 'Canal Street gets its name from an actual canal that once drained the Collect Pond — Manhattan\'s main freshwater source — into the Hudson River in the early 1800s.',
    exits: ['Canal St & 8th Ave', 'Varick St & Canal St'],
  },
  {
    id: 'fulton-st',
    name: 'Fulton St',
    lines: ['2', '3', '4', '5', 'A', 'C', 'J', 'Z'],
    borough: 'Manhattan',
    lat: 40.7098, lng: -74.0092,
    svgNodeId: 'n-fulton',
    funFact: 'The Fulton Center, opened in 2014, is built directly above an 1868 cast-iron commercial building. Its interior dome creates a sky-reflecting oculus 53 feet wide.',
    exits: ['Fulton St & Broadway', 'Dey St', 'Church St & Fulton St'],
  },
  {
    id: 'world-trade-center',
    name: 'World Trade Center',
    lines: ['E'],
    borough: 'Manhattan',
    lat: 40.7127, lng: -74.0099,
    svgNodeId: 'n-wtc',
    funFact: 'The Oculus transportation hub, above this station, was designed by Santiago Calatrava. Its wings open each September 11 at 10:28 AM — the moment the second tower fell — letting sunlight fall on the footprints of the towers.',
    exits: ['Cortlandt St', 'Church St & Liberty St'],
  },
  {
    id: 'south-ferry',
    name: 'South Ferry',
    lines: ['1'],
    borough: 'Manhattan',
    lat: 40.7014, lng: -74.0131,
    svgNodeId: 'n-south-ferry',
    funFact: 'The original 1905 South Ferry station loop had a sharp 180° curve so tight that most of the train doors opened into the wall — passengers could only board from the first 5 cars.',
    exits: ['Battery Park', 'Whitehall St'],
  },

  // ──────────────────────────── THE BRONX ───────────────────────────

  {
    id: '161-yankee',
    name: '161 St-Yankee Stadium',
    lines: ['4', 'B', 'D'],
    borough: 'Bronx',
    lat: 40.8276, lng: -73.9252,
    svgNodeId: 'n-yankee',
    funFact: 'Yankee Stadium has witnessed 27 World Series championships — more than any other team in baseball history.',
    exits: ['River Ave & 161 St', '157 St & River Ave'],
  },
  {
    id: '149-grand-concourse',
    name: '149 St-Grand Concourse',
    lines: ['2', '5'],
    borough: 'Bronx',
    lat: 40.8181, lng: -73.9271,
    svgNodeId: 'n-149-gc',
    funFact: 'The Grand Concourse, modeled on Paris\'s Champs-Élysées, was designed in 1892 as a 4.5-mile grand boulevard connecting the Bronx to Manhattan.',
    exits: ['Third Ave & 149 St', 'Willis Ave & 149 St'],
  },
  {
    id: 'fordham-rd',
    name: 'Fordham Rd',
    lines: ['4', 'B', 'D'],
    borough: 'Bronx',
    lat: 40.8615, lng: -73.8971,
    svgNodeId: 'n-fordham',
    funFact: 'Fordham Road is the Bronx\'s busiest commercial corridor and one of the highest-grossing retail strips in all of New York City.',
    exits: ['Grand Concourse & Fordham Rd', 'Jerome Ave & Fordham Rd'],
  },
  {
    id: 'pelham-bay-park',
    name: 'Pelham Bay Park',
    lines: ['6'],
    borough: 'Bronx',
    lat: 40.8525, lng: -73.8282,
    svgNodeId: 'n-pelham-bay',
    funFact: 'Pelham Bay Park is the largest park in New York City at 2,772 acres — nearly three times the size of Central Park — with 13 miles of shoreline.',
    exits: ['Bruckner Blvd & Wilkinson Ave'],
  },
  {
    id: 'woodlawn',
    name: 'Woodlawn',
    lines: ['4'],
    borough: 'Bronx',
    lat: 40.8863, lng: -73.8782,
    svgNodeId: 'n-woodlawn',
    funFact: 'Woodlawn Cemetery, adjacent to this station, is a National Historic Landmark and the final resting place of Duke Ellington, Miles Davis, and Herman Melville.',
    exits: ['Webster Ave & E 233 St'],
  },

  // ─────────────────────────── BROOKLYN ─────────────────────────────

  {
    id: 'atlantic-barclays',
    name: 'Atlantic Ave-Barclays Ctr',
    lines: ['2', '3', '4', '5', 'B', 'D', 'N', 'Q', 'R'],
    borough: 'Brooklyn',
    lat: 40.6843, lng: -73.9776,
    svgNodeId: 'n-atlantic',
    funFact: 'Beneath Atlantic Avenue runs an 1844 tunnel — the oldest subway tunnel in the world — built for the Long Island Rail Road and sealed for over 100 years before its rediscovery in 1980.',
    exits: ['Atlantic Ave & 4th Ave', 'Flatbush Ave & Atlantic Ave', 'Dean St'],
  },
  {
    id: 'jay-st-metrotech',
    name: 'Jay St-MetroTech',
    lines: ['A', 'C', 'F', 'R'],
    borough: 'Brooklyn',
    lat: 40.6922, lng: -73.9872,
    svgNodeId: 'n-jay-st',
    funFact: 'MetroTech Center, the tech campus above, was one of NYC\'s first major efforts to attract technology companies to Brooklyn, beginning in the early 1990s.',
    exits: ['Jay St & Willoughby St', 'Jay St & Fulton St', 'Jay St & Myrtle Ave'],
  },
  {
    id: 'bedford-ave',
    name: 'Bedford Ave',
    lines: ['L'],
    borough: 'Brooklyn',
    lat: 40.7171, lng: -73.9561,
    svgNodeId: 'n-bedford',
    funFact: 'Bedford Avenue station is the epicenter of Williamsburg and one of the first stations to receive custom mosaic art — its 2016 renovation features over 1,200 hand-cut tiles depicting local scenes.',
    exits: ['Bedford Ave & N 7 St', 'Bedford Ave & N 8 St'],
  },
  {
    id: '7-ave-park-slope',
    name: '7 Av',
    lines: ['B', 'Q'],
    borough: 'Brooklyn',
    lat: 40.6770, lng: -73.9724,
    svgNodeId: 'n-7ave-ps',
    funFact: 'Park Slope, directly above, was named by the New York Times the "Best Neighborhood in New York City" in 2010 and is home to the second-largest food co-op in the US.',
    exits: ['7th Ave & Flatbush Ave', '7th Ave & Sterling Pl'],
  },
  {
    id: 'flatbush-ave',
    name: 'Flatbush Av-Brooklyn College',
    lines: ['2', '5'],
    borough: 'Brooklyn',
    lat: 40.6320, lng: -73.9474,
    svgNodeId: 'n-flatbush',
    funFact: 'Brooklyn College above was the first public college in New York City to offer a liberal arts education. Its Georgian Revival campus was called "the most beautiful college campus in the East" by the American Institute of Architects.',
    exits: ['Flatbush Ave & Nostrand Ave'],
  },
  {
    id: 'coney-island-stillwell',
    name: 'Coney Island-Stillwell Av',
    lines: ['D', 'F', 'N', 'Q'],
    borough: 'Brooklyn',
    lat: 40.5775, lng: -73.9813,
    svgNodeId: 'n-coney',
    funFact: 'Coney Island was home to the world\'s first roller coasters in the 1880s. The Cyclone, built in 1927 and still operating, was declared a NYC landmark in 1988.',
    exits: ['Stillwell Ave & Surf Ave'],
  },
  {
    id: 'brighton-beach',
    name: 'Brighton Beach',
    lines: ['B', 'Q'],
    borough: 'Brooklyn',
    lat: 40.5775, lng: -73.9613,
    svgNodeId: 'n-brighton',
    funFact: 'Brighton Beach is known as "Little Odessa" due to its large Russian-speaking immigrant community. The boardwalk here was built in 1906 and stretches 2.7 miles to Coney Island.',
    exits: ['Brighton Beach Ave & Brighton 1 St'],
  },
  {
    id: 'bay-ridge-95',
    name: 'Bay Ridge-95 St',
    lines: ['R'],
    borough: 'Brooklyn',
    lat: 40.6163, lng: -74.0309,
    svgNodeId: 'n-bay-ridge',
    funFact: 'Bay Ridge was the filming location for John Travolta\'s Saturday Night Fever in 1977. The Verrazzano-Narrows Bridge, visible from the station, was the world\'s longest suspension bridge when built in 1964.',
    exits: ['4th Ave & 95 St'],
  },
  {
    id: 'howard-beach',
    name: 'Howard Beach-JFK Airport',
    lines: ['A'],
    borough: 'Queens',
    lat: 40.6603, lng: -73.8303,
    svgNodeId: 'n-howard-beach',
    funFact: 'This station connects to the AirTrain, which opened in 2003 and was one of the first dedicated rail links between NYC and its airports.',
    exits: ['Coleman Square', 'Linden Blvd & 159 St'],
  },
  {
    id: 'canarsie',
    name: 'Canarsie-Rockaway Pkwy',
    lines: ['L'],
    borough: 'Brooklyn',
    lat: 40.6464, lng: -73.9013,
    svgNodeId: 'n-canarsie',
    funFact: 'The L train\'s route from here to 8th Ave in Manhattan traverses the first tunnel built directly under the East River using modern "cut-and-cover" methods, completed in 1924.',
    exits: ['Rockaway Pkwy & Glenwood Rd'],
  },

  // ──────────────────────────── QUEENS ──────────────────────────────

  {
    id: 'flushing-main',
    name: 'Flushing-Main St',
    lines: ['7'],
    borough: 'Queens',
    lat: 40.7592, lng: -73.8303,
    svgNodeId: 'n-flushing',
    funFact: 'Flushing\'s Main Street is one of the most linguistically diverse streets in the world, with storefronts in over 20 languages, and is the largest Chinatown outside of China.',
    exits: ['Main St & Roosevelt Ave', 'Main St & 41 Ave'],
  },
  {
    id: 'jackson-heights',
    name: 'Jackson Heights-Roosevelt Ave',
    lines: ['7', 'E', 'F', 'M', 'R'],
    borough: 'Queens',
    lat: 40.7464, lng: -73.8912,
    svgNodeId: 'n-jackson-heights',
    funFact: 'Jackson Heights is one of the most ethnically diverse urban areas on Earth, with over 160 languages spoken among its 170,000 residents.',
    exits: ['Roosevelt Ave & 74 St', 'Jackson Heights & 73 St'],
  },
  {
    id: 'astoria-ditmars',
    name: 'Astoria-Ditmars Blvd',
    lines: ['N', 'W'],
    borough: 'Queens',
    lat: 40.7753, lng: -73.9122,
    svgNodeId: 'n-astoria-ditmars',
    funFact: 'Astoria was the film production capital of the world in the silent film era. The Kaufman Astoria Studios here, built in 1920, still operates today and produced films from The Marx Brothers to Sesame Street.',
    exits: ['Ditmars Blvd & 31 St', '31 St & Ditmars Blvd'],
  },
  {
    id: 'court-sq',
    name: 'Court Sq',
    lines: ['E', 'G', 'M', '7'],
    borough: 'Queens',
    lat: 40.7468, lng: -73.9454,
    svgNodeId: 'n-court-sq',
    funFact: 'Long Island City, around Court Square, has seen the most dramatic gentrification in Queens. It was once home to more industrial space per square mile than any other NYC neighborhood.',
    exits: ['Jackson Ave & Queens Plaza N', 'Court Sq & 23 St'],
  },
  {
    id: 'jamaica-center',
    name: 'Jamaica Center-Parsons/Archer',
    lines: ['E', 'J', 'Z'],
    borough: 'Queens',
    lat: 40.7022, lng: -73.8015,
    svgNodeId: 'n-jamaica',
    funFact: 'Jamaica Avenue was a Native American trail for thousands of years before European colonization — the Lenape called this corridor "Jameco," meaning "beaver." It is now one of Queens\'s main commercial arteries.',
    exits: ['Parsons Blvd & Archer Ave', 'Jamaica Ave & 169 St'],
  },
  {
    id: 'forest-hills',
    name: 'Forest Hills-71 Av',
    lines: ['E', 'F', 'M', 'R'],
    borough: 'Queens',
    lat: 40.7212, lng: -73.8468,
    svgNodeId: 'n-forest-hills',
    funFact: 'Forest Hills Gardens, adjacent to this station, was built in 1909 as one of America\'s first planned garden communities and was modeled on English garden city principles.',
    exits: ['Continental Ave & Queens Blvd', '71 Ave & Austin St'],
  },
  {
    id: 'mets-willets-point',
    name: 'Mets-Willets Point',
    lines: ['7'],
    borough: 'Queens',
    lat: 40.7543, lng: -73.8456,
    svgNodeId: 'n-mets',
    funFact: 'Citi Field, next to this station, was built on top of the old Flushing Meadows landfill — the same "valley of ashes" F. Scott Fitzgerald immortalized in The Great Gatsby.',
    exits: ['Northern Blvd & 126 St'],
  },
  {
    id: 'far-rockaway',
    name: 'Far Rockaway-Mott Av',
    lines: ['A'],
    borough: 'Queens',
    lat: 40.6052, lng: -73.7561,
    svgNodeId: 'n-far-rock',
    funFact: 'The Rockaways form NYC\'s only ocean barrier beach — an 11-mile peninsula that took the full brunt of Hurricane Sandy in 2012, yet rebuilt with remarkable resilience.',
    exits: ['Mott Ave & Central Ave'],
  },
  {
    id: 'rockaway-park',
    name: 'Rockaway Park-Beach 116 St',
    lines: ['A', 'S'],
    borough: 'Queens',
    lat: 40.5800, lng: -73.8177,
    svgNodeId: 'n-rockaway-park',
    funFact: 'The Rockaways were the summer destination for millions of New Yorkers in the early 1900s before air conditioning. The Jacob Riis Park beach here was once called the "Poor Man\'s Riviera."',
    exits: ['Rockaway Beach Blvd & 116 St'],
  },

  // ─────────────────────────── STATEN ISLAND ────────────────────────

  {
    id: 'st-george',
    name: 'St George',
    lines: ['SIR'],
    borough: 'Staten Island',
    lat: 40.6435, lng: -74.0741,
    svgNodeId: 'n-st-george',
    funFact: 'The Staten Island Ferry, which departs from St. George terminal, carries 25 million riders per year — and has been free since 1997. It offers one of the best views of the Statue of Liberty in New York.',
    exits: ['St George Ferry Terminal', 'Richmond Terrace & Bay St'],
  },
  {
    id: 'stapleton',
    name: 'Stapleton',
    lines: ['SIR'],
    borough: 'Staten Island',
    lat: 40.6276, lng: -74.0749,
    svgNodeId: 'n-stapleton',
    funFact: 'Stapleton\'s waterfront was the site of a Navy homeport base during the Cold War. The area has seen a major artistic and cultural renaissance since the 2010s.',
    exits: ['Bay St & Wright St'],
  },
  {
    id: 'tottenville',
    name: 'Tottenville',
    lines: ['SIR'],
    borough: 'Staten Island',
    lat: 40.5120, lng: -74.2519,
    svgNodeId: 'n-tottenville',
    funFact: 'Tottenville is the southernmost point in New York State and one of the least densely populated neighborhoods in all five boroughs. Its Conference House park contains a manor where Benjamin Franklin attempted peace negotiations during the Revolutionary War.',
    exits: ['Main St & Bentley St'],
  },
];

/**
 * Look up a station by its ID.
 * @param {string} id
 * @returns {object|undefined}
 */
export function getStationById(id) {
  return STATIONS.find(s => s.id === id);
}

/**
 * Get all unique MTA lines present in the dataset.
 * @returns {string[]}
 */
export function getAllLines() {
  const lines = new Set();
  STATIONS.forEach(s => s.lines.forEach(l => lines.add(l)));
  return [...lines].sort();
}

/**
 * Get stations filtered by borough.
 * @param {string} borough
 * @returns {object[]}
 */
export function getStationsByBorough(borough) {
  return STATIONS.filter(s => s.borough === borough);
}
